spring:
  application:
    name: batch-cmdm-import
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jdbc:
    query-timeout:
      template: 30000ms
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: ecomerce
        jdbc:
          lob:
            non_contextual_creation: true # Disable contextual LOB creation
  sql:
    init:
      schema-locations: schema-all.sql
      mode: always
      continue-on-error: true
      platform: all
  jmx:
    enabled: false # Disable management beans

mjarray:
  mvc:
    overview:
      enable: false
  batch:
    config:
      partitioner:
        chunk-size: 100
        max-pool-size: 50
      step:
        chunk-size: 100
        max-pool-size: 50
      files:
        tar-file-name-pattern: (ecomerce_import)(.*)\.tgz$
        column-delimiter: '|'
        order-file-prefix: order
        product-file-prefix: product
        sale-file-prefix: sale
      order-status:
          - PAIED
          - EXPIRED
          - IN_PROGRESS
  datasource-master:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecomerce # started in a Docker container, see docker-compose.yml
    password: admin
    username: admin
    continue-on-error: true
    platform: all
    initialization-mode: always
    hikari:
      maximum-pool-size: 100
      minimum-idle: 2
      data-source-properties:
        socketTimeout: 120
  datasource-readonly:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecomerce # started in a Docker container, see docker-compose.yml
    password: admin
    username: admin
    hikari:
      maximum-pool-size: 100
      minimum-idle: 2
      data-source-properties:
        socketTimeout: 120
        
logging:
  level:
    org.springframework.jdbc: DEBUG
    com.renault.wired: DEBUG